//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.15 at 12:41:08 PM CST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.sat.gob.mx/TimbreFiscalDigital", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.usanchez.procesa_xml_sat.domain;
